name: Deploy site100honey

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REGRU_HOST }}
          username: ${{ secrets.REGRU_USER }}
          key: ${{ secrets.REGRU_KEY }}
          script: |
            cd /var/www/u1538455/data/www/медовые-подарки.рф/wp-content/themes/honey-present-wordpress-theme
            git clone git@github.com:site100ru/honey-present-wordpress-theme.git .
            
            #cd /var/www/u1538455/data/www/медовые-подарки.рф/wp-content/themes/honey-present-wordpress-theme
            #git pull
